#!/usr/bin/env python3
"""
build_backlog.py — generate `BACKLOG.md` from coverage gaps + TAXONOMY-GAPS
proposals + per-Tactic minimum-coverage targets.

The output is a prioritized contributor-onboarding document: "here is what
OAK needs documented, ranked by leverage." Contributors can claim items via
GitHub issues / PRs; the file regenerates from corpus state on every build.

Usage:
    python3 tools/build_backlog.py > BACKLOG.md

Exit code is always 0; this is a reporting tool.
"""

from __future__ import annotations

import datetime as dt
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

YEAR_RE = re.compile(r"^(\d{4})")
TECH_RE = re.compile(r"\bOAK-T(\d+)\.\d+(?:\.\d+)?\b")
ACTOR_RE = re.compile(r"\bOAK-G\d{2}\b")
TECH_FULL_RE = re.compile(r"\bOAK-T\d+(?:\.\d+){1,2}\b")
PLACEHOLDER_RE = re.compile(r"\bOAK-(?:G|T|M|S)nn\b")

# Per-Tactic minimum-coverage targets. Active years differ per Tactic — e.g.
# Account Abstraction (T13) only became deployable at scale in 2024 with
# ERC-4337 production. Each entry: (tactic_id, name, active_since, min_per_year).
COVERAGE_TARGETS = [
    ("T1", "Token Genesis", 2020, 5),
    ("T2", "Liquidity Establishment", 2020, 3),
    ("T3", "Holder Capture", 2021, 2),
    ("T4", "Access Acquisition", 2020, 4),
    ("T5", "Value Extraction", 2020, 4),
    ("T6", "Defense Evasion", 2022, 2),
    ("T7", "Laundering", 2018, 4),
    ("T8", "Operational Reuse", 2020, 3),
    ("T9", "Smart-Contract Exploit", 2020, 5),
    ("T10", "Bridge / Cross-Chain", 2021, 3),
    ("T11", "Custody / Signing", 2018, 3),
    ("T12", "NFT-Specific", 2021, 2),
    ("T13", "Account Abstraction", 2024, 3),
    ("T14", "Validator / Staking", 2023, 3),
    ("T15", "Off-chain Entry-Vector / Pre-Positioning", 2017, 3),
]


def parse_examples():
    items = []
    for p in sorted((REPO / "examples").glob("*.md")):
        if p.name.lower() == "readme.md":
            continue
        text = p.read_text(encoding="utf-8")
        m = YEAR_RE.match(p.name)
        year = int(m.group(1)) if m else None
        cleaned = PLACEHOLDER_RE.sub("", text)
        tactics = {int(t) for t in TECH_RE.findall(cleaned)}
        techniques = set(TECH_FULL_RE.findall(cleaned))
        actors = set(ACTOR_RE.findall(cleaned))
        items.append({"name": p.name, "year": year, "tactics": tactics, "techniques": techniques, "actors": actors})
    return items


def technique_inventory():
    out = []
    for f in sorted((REPO / "techniques").glob("T*.md")):
        m = re.match(r"^(T\d+(?:\.\d+){1,2})-(.+?)\.md$", f.name)
        if m:
            out.append((f"OAK-{m.group(1)}", m.group(2).replace("-", " ")))
    return out


def actor_inventory():
    out = []
    for f in sorted((REPO / "actors").glob("OAK-G*.md")):
        m = re.match(r"^(OAK-G\d{2})-(.+?)\.md$", f.name)
        if m:
            out.append((m.group(1), m.group(2).replace("-", " ")))
    return out


def main() -> int:
    examples = parse_examples()
    techniques = technique_inventory()
    actors = actor_inventory()
    today = dt.date.today().isoformat()

    by_year_tactic: dict[tuple[int, int], int] = Counter()
    by_tactic: Counter[int] = Counter()
    by_technique: Counter[str] = Counter()
    by_actor: Counter[str] = Counter()
    for e in examples:
        if e["year"] is None:
            continue
        for t in e["tactics"]:
            by_year_tactic[(e["year"], t)] += 1
            by_tactic[t] += 1
        for tech in e["techniques"]:
            by_technique[tech] += 1
        for a in e["actors"]:
            by_actor[a] += 1

    current_year = dt.date.today().year

    out: list[str] = []
    out.append("# OAK Backlog — auto-generated\n")
    out.append(f"_Generated by `tools/build_backlog.py` on {today}. Regenerated on every `npm run site:data`._\n")
    out.append(f"_Scope: {len(examples)} worked examples, {len(techniques)} Techniques, {len(actors)} Threat Actors._\n")
    out.append("This file is a prioritized contributor backlog. **P0** items close hard structural gaps (empty Tactics, placeholder actor cards). **P1** items lift per-Tactic coverage below the documented minimum. **P2** items anchor candidate sub-Techniques from `TAXONOMY-GAPS.md`.\n")
    out.append("Before researching a candidate incident, run `python3 tools/check_known.py \"<description>\"` to avoid duplicating an existing entry.\n")

    out.append("## P0 — empty Tactics × active years\n")
    out.append("Each (Tactic, year) cell below has zero documented incidents despite the Tactic being active in that year. Closing these is the highest leverage for matrix completeness.\n")
    p0: list[str] = []
    for tactic_id, name, active_since, min_per_year in COVERAGE_TARGETS:
        t_num = int(tactic_id[1:])
        for year in range(max(active_since, 2018), current_year + 1):
            if by_year_tactic.get((year, t_num), 0) == 0:
                p0.append(f"- **{tactic_id} × {year}** ({name}) — 0 / target ≥1")
    out.extend(p0[:40] if p0 else ["- _no empty cells in active years_"])
    if len(p0) > 40:
        out.append(f"- _… and {len(p0) - 40} more cells_")
    out.append("")

    out.append("## P0 — actor profiles without attributed incidents\n")
    inactive_actors = [(aid, name) for aid, name in actors if by_actor.get(aid, 0) == 0]
    if inactive_actors:
        for aid, name in inactive_actors:
            out.append(f"- **{aid}** ({name}) — actor card exists, 0 worked examples attribute this actor")
    else:
        out.append("- _all actor cards have at least one attributed example_")
    out.append("")

    out.append("## P0 — sub-Techniques without canonical anchor\n")
    no_anchor = [(tid, name) for tid, name in techniques if by_technique.get(tid, 0) == 0]
    if no_anchor:
        for tid, name in no_anchor:
            out.append(f"- **{tid}** ({name}) — defined in `techniques/`, 0 referencing examples")
    else:
        out.append("- _all sub-Techniques have at least one referencing example_")
    out.append("")

    out.append("## P1 — Tactics under per-year minimum coverage\n")
    out.append("Tactics where the documented incident count for an active year falls below the target threshold (see `COVERAGE-TARGETS.md`).\n")
    p1: list[str] = []
    for tactic_id, name, active_since, min_per_year in COVERAGE_TARGETS:
        t_num = int(tactic_id[1:])
        for year in range(max(active_since, 2020), current_year + 1):
            actual = by_year_tactic.get((year, t_num), 0)
            if 0 < actual < min_per_year:
                p1.append(f"- **{tactic_id} × {year}** ({name}) — {actual} / target ≥{min_per_year}")
    out.extend(p1[:40] if p1 else ["- _all active-year cells meet the per-Tactic minimum_"])
    if len(p1) > 40:
        out.append(f"- _… and {len(p1) - 40} more cells_")
    out.append("")

    out.append("## P2 — TAXONOMY-GAPS candidates without an example anchor\n")
    out.append("Sub-Technique IDs proposed in `TAXONOMY-GAPS.md` but not yet referenced by any worked example. Promoting these to `emerging` requires at least one anchor case.\n")
    gaps_path = REPO / "TAXONOMY-GAPS.md"
    proposed_ids: set[str] = set()
    if gaps_path.exists():
        gaps_text = gaps_path.read_text(encoding="utf-8")
        for m in re.finditer(r"\bT(\d+)\.(\d+)(?:\.(\d+))?\b", gaps_text):
            full = f"OAK-T{m.group(1)}.{m.group(2)}"
            if m.group(3):
                full += f".{m.group(3)}"
            proposed_ids.add(full)
    real_ids = {tid for tid, _ in techniques}
    candidate_orphans = sorted(proposed_ids - real_ids - set(by_technique.keys()))
    if candidate_orphans:
        for cid in candidate_orphans:
            out.append(f"- **{cid}** — proposed in TAXONOMY-GAPS, 0 referencing examples")
    else:
        out.append("- _all candidates are either anchored or already promoted_")
    out.append("")

    out.append("## How to claim an item")
    out.append("")
    out.append("1. Pick a P0 / P1 / P2 line item that matches your research interest.")
    out.append("2. Run `python3 tools/check_known.py \"<incident description>\"` against your candidate to confirm it isn't already documented.")
    out.append("3. Open a GitHub issue with the line item title (e.g. `[backlog] T13 × 2024 — paymaster compromise candidate`) so others can see what's claimed.")
    out.append("4. Submit a PR per CONTRIBUTING.md. The PR template has a Checklist that runs the validators locally.")

    # Single trailing newline; collapse any accidental double-blanks first.
    body = "\n".join(out)
    body = re.sub(r"\n{3,}", "\n\n", body).rstrip() + "\n"
    sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
