#!/usr/bin/env python3
"""Generate SPECS.md — repo-side index of detection specs grouped by Tactic.

Reads tools/specs.json (produced by build_specs.py) and tools/oak.json
(canonical Tactic / Technique catalogue) and emits a single markdown file
listing every Technique with its spec status (maturity badge + path) for
GitHub-side browsing.

Run after build_specs.py:

    python3 tools/build_specs.py && python3 tools/build_specs_index.py
"""
from __future__ import annotations
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "SPECS.md"


def technique_sort_key(tid: str) -> tuple[int, ...]:
    nums = re.findall(r"\d+", tid)
    return tuple(int(n) for n in nums)


def maturity_badge(m: str) -> str:
    return {
        "stable": "🟢 stable",
        "observed": "🔵 observed",
        "emerging": "🟡 emerging",
        "draft": "⚪ draft",
        "deprecated": "⚫ deprecated",
    }.get(m, m)


def main() -> None:
    specs_doc = json.loads((REPO / "tools" / "specs.json").read_text())
    oak = json.loads((REPO / "tools" / "oak.json").read_text())

    tactics = {t["id"]: t for t in oak["tactics"]}
    techniques = {t["id"]: t for t in oak["techniques"]}

    # Index specs by Technique ID (one Technique → potentially multiple specs).
    spec_by_tech: dict[str, list[dict]] = {}
    for s in specs_doc["specs"]:
        for tid in s["oak_techniques"]:
            spec_by_tech.setdefault(tid, []).append(s)

    total_specs = len(specs_doc["specs"])
    total_techs = len(techniques)
    covered = sum(1 for tid in techniques if tid in spec_by_tech)

    by_tactic: dict[str, list[str]] = {}
    for tid in techniques:
        # parent tactic = first numeric component → OAK-T<n>
        m = re.match(r"OAK-T(\d+)", tid)
        if not m:
            continue
        tac = f"OAK-T{m.group(1)}"
        by_tactic.setdefault(tac, []).append(tid)

    maturity_counts = {"stable": 0, "observed": 0, "emerging": 0, "draft": 0}
    for s in specs_doc["specs"]:
        maturity_counts[s["maturity"]] = maturity_counts.get(s["maturity"], 0) + 1

    lines = [
        "# OAK Detection Specs — Index",
        "",
        "_Auto-generated by `tools/build_specs_index.py` from `tools/specs.json`. "
        "Do not edit by hand._",
        "",
        f"**Coverage:** {covered}/{total_techs} Techniques "
        f"({covered / total_techs:.0%}) · {total_specs} specs across "
        f"{len(by_tactic)} Tactics.",
        "",
        f"**Maturity distribution:** "
        f"{maturity_counts.get('stable', 0)} stable · "
        f"{maturity_counts.get('observed', 0)} observed · "
        f"{maturity_counts.get('emerging', 0)} emerging · "
        f"{maturity_counts.get('draft', 0)} draft.",
        "",
        "Specs are vendor-neutral, language-agnostic YAML detection specs "
        "(one per Technique). Each spec carries `data_sources`, "
        "`detection_logic.pseudocode` (orthogonal `PATH A / PATH B / ...` paths), "
        "`parameters`, `test_fixtures`, `false_positive_modes`, "
        "`mitigations` cross-refs, and `reference_implementations`. "
        "Schema is Sigma-shape — the closest existing-format analogue is "
        "Sigma rules aligned to MITRE ATT&CK. See "
        "[`CONTRIBUTING.md`](./CONTRIBUTING.md) for the spec-authoring "
        "convention and [`tools/build_specs.py`](./tools/build_specs.py) "
        "for the validator.",
        "",
        "Maturity legend:",
        "",
        "- 🟢 `stable` — multi-anchor, multi-vendor agreement, positive fixture present.",
        "- 🔵 `observed` — field-confirmed at single anchor, cross-vendor agreement still pending.",
        "- 🟡 `emerging` — recently introduced; small worked-example set.",
        "- ⚪ `draft` — definition still consolidating; no positive fixture.",
        "",
        "---",
        "",
    ]

    for tac in sorted(by_tactic, key=technique_sort_key):
        tactic_meta = tactics.get(tac, {})
        name = tactic_meta.get("name", tac)
        techs_in_tactic = sorted(by_tactic[tac], key=technique_sort_key)
        covered_in_tactic = sum(1 for t in techs_in_tactic if t in spec_by_tech)
        ratio = covered_in_tactic / len(techs_in_tactic)
        status_icon = "✅" if ratio == 1.0 else ("⚠️" if ratio > 0 else "⚪")

        lines.append(
            f"## {status_icon} {tac} — {name} "
            f"({covered_in_tactic}/{len(techs_in_tactic)})"
        )
        lines.append("")
        lines.append("| Technique | Maturity | Spec |")
        lines.append("|---|---|---|")

        for tid in techs_in_tactic:
            tech_meta = techniques.get(tid, {})
            tech_name = tech_meta.get("name", "")
            specs_for = spec_by_tech.get(tid, [])
            if not specs_for:
                lines.append(f"| `{tid}` — {tech_name} | — | _(no spec)_ |")
                continue
            for s in specs_for:
                badge = maturity_badge(s["maturity"])
                spec_path = s["path"]
                lines.append(
                    f"| `{tid}` — {tech_name} | {badge} | "
                    f"[`{spec_path.split('/')[-1]}`](./{spec_path}) |"
                )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Updated automatically when `tools/build_specs_index.py` runs as part "
        "of `npm run site:data`. Last regenerated from corpus state at "
        f"`{specs_doc.get('generated_at', 'unknown')}`."
    )
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"OK: wrote {OUT.relative_to(REPO)} — "
          f"{covered}/{total_techs} Techniques, "
          f"{total_specs} specs, "
          f"{len(by_tactic)} Tactics")


if __name__ == "__main__":
    main()
